language: go
go_import_path: github.com/operator-framework/operator-sdk
sudo: required
dist: xenial
go:
  - 1.12.x
services:
  - docker
script:
  - export GO111MODULE=on
  - operator-sdk build registry.cn-shenzhen.aliyuncs.com/jaywoods/nginx-operator:v0.0.1
  - docker login --username=${USER} -p ${PASSWORD}  registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/jaywoods/nginx-operator:v0.0.1
