apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxservices.nginx.kubernetes.io
spec:
  group: nginx.kubernetes.io
  names:
    kind: NginxService
    listKind: NginxServiceList
    plural: nginxservices
    singular: nginxservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            envs:
              items:
                type: object
              type: array
            image:
              type: string
            ports:
              items:
                type: object
              type: array
            resources:
              type: object
            size:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int32
              type: integer
          required:
          - size
          - image
          type: object
        status:
          properties:
            availableReplicas:
              description: Total number of available pods (ready for at least minReadySeconds)
                targeted by this deployment.
              format: int32
              type: integer
            collisionCount:
              description: Count of hash collisions for the Deployment. The Deployment
                controller uses this field as a collision avoidance mechanism when
                it needs to create the name for the newest ReplicaSet.
              format: int32
              type: integer
            conditions:
              description: Represents the latest available observations of a deployment's
                current state. +patchMergeKey=type +patchStrategy=merge
              items:
                type: object
              type: array
            observedGeneration:
              description: The generation observed by the deployment controller.
              format: int64
              type: integer
            readyReplicas:
              description: Total number of ready pods targeted by this deployment.
              format: int32
              type: integer
            replicas:
              description: Total number of non-terminated pods targeted by this deployment
                (their labels match the selector).
              format: int32
              type: integer
            unavailableReplicas:
              description: Total number of unavailable pods targeted by this deployment.
                This is the total number of pods that are still required for the deployment
                to have 100% available capacity. They may either be pods that are
                running but not yet available or pods that still have not been created.
              format: int32
              type: integer
            updatedReplicas:
              description: Total number of non-terminated pods targeted by this deployment
                that have the desired template spec.
              format: int32
              type: integer
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
